<?php

namespace AirServer;

use Blackwater\Servers\BlackwaterBasicServer;
use Ratchet\ConnectionInterface;

/**
 * This class has been generated by the Blackwater client.
 * This is the core class of your server application.
 *
 * Class AirServer
 * @package AirServer
 */
class AirServer extends BlackwaterBasicServer
{

    /**
     * Triggered when a client sends data through the socket.
     * This is the only method that must be overrided. The core logic for the server goes here.
     *
     * @param  ConnectionInterface $from The socket/connection that sent the message to your application
     * @param  string $msg The message received
     * @throws \Exception
     */
    function onMessage(ConnectionInterface $from, $msg)
    {
        // TODO: Implement onMessage() method.
    }
}